//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/NSArray.h>
#import <UIAutomation/UIAElement.h>

@interface UIAPickerWheel : UIAElement
{
}

- (void)selectValue:(id)value;
- (_Bool)_spinWheel:(long long)arg1;
- (NSArray*)values;
- (id)elements;

@end

