//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIAutomation/UIAElement.h>
#import <UIAutomation/UIARemote.h>
#import <UIAutomation/UIAWindow.h>
#import <UIAutomation/UIAApplication.h>
#import <UIAutomation/UIAScreen.h>
#import <UIAutomation/UIASyntheticStarkEvents.h>

@class CLSimulationManager, NSDate, NSString, UIAHost;

@interface UIATarget : UIAElement
{
    NSDate *_startupDate;
    long long _textViewValueMaxLength;
    long long _interfaceOrientation;
    double _lastAnimationEndedTime;
    NSString *_nameOfLastApp;
    UIAHost *_host;
    CLSimulationManager *_locationSimulationManager;
    _Bool _logElementTakesScreenshot;
    _Bool _handlesAlerts;
    unsigned long long valueChangedCount;
    UIASyntheticEvents *_eventGenerator;
    UIASyntheticStarkEvents *_starkEventGenerator;
}

+ (id)toManyRelationshipKeys;
+ (id)toOneRelationshipKeys;
+ (id)attributeKeys;
+ (id)_locationForObject:(id)arg1 withOptions:(id)arg2;
+ (UIATarget*)localTarget;
@property(readonly) UIASyntheticStarkEvents *starkEventGenerator; // @synthesize starkEventGenerator=_starkEventGenerator;
@property(readonly) UIASyntheticEvents *eventGenerator; // @synthesize eventGenerator=_eventGenerator;
@property unsigned long long valueChangedCount; // @synthesize valueChangedCount;
@property _Bool handlesAlerts; // @synthesize handlesAlerts=_handlesAlerts;
@property _Bool logElementTakesScreenshot; // @synthesize logElementTakesScreenshot=_logElementTakesScreenshot;
- (_Bool)reactivateApp;
- (_Bool)deactivateApp;
- (_Bool)deactivateAppForDuration:(id)duration;
- (_Bool)unlock;
- (_Bool)unlockWithOptions:(id)arg1;
- (void)_enterPasscode:(id)arg1;
- (void)_tapPictureFrame:(id)arg1;
- (void)_slideToCamera:(id)arg1;
- (void)_slideToUnlock:(id)arg1;
- (id)_lockScreenScrollView;
- (_Bool)lock;
- (_Bool)lockForDuration:(id)arg1;
- (_Bool)isScreenOff;
- (_Bool)isLocked;
- (void)setRinger:(id)arg1;
- (void)holdVolumeDown:(id)arg1;
- (void)clickVolumeDown;
- (void)holdVolumeUp:(NSNumber*)duration;
- (void)clickVolumeUp;
- (void)holdLock:(NSNumber*)duration;
- (void)clickLock;
- (void)holdMenu:(NSNumber*)duration;
- (void)clickMenu;
- (void)shake;
- (void)rotate:(NSValue*)centerPoint withOptions:(NSDictionary*)options;
- (void)pinchOpenFrom:(NSValue*)fromPoint to:(NSValue*)toPoint forDuration:(NSString*)duration;
- (void)pinchCloseFrom:(NSValue*)fromPoint to:(NSValue*)toPoint forDuration:(NSString*)duration;
- (void)flickFrom:(NSValue*)fromPoint to:(NSValue*)toPoint;
- (void)dragFrom:(NSValue*)fromPoint to:(NSValue*)toPoint forDuration:(NSString*)duration;
//@see https://developer.apple.com/library/ios/#documentation/ToolsLanguages/Reference/UIATargetClassReference/UIATargetClass/UIATargetClass.html%23//apple_ref/doc/uid/TP40009924-CH3-SW41
- (void)touch:(id)arg1 andHold:(id)arg2;
- (void)touch:(id)arg1 withOptions:(id)arg2;
- (void)touch:(id)arg1;
- (_Bool)_touch:(id)arg1 withOptions:(id)arg2;
- (void)tap:(NSValue*)point withOptions:(NSDictionary*)options;
- (void)twoFingerTap:(NSValue*)point;
- (void)doubleTap:(NSValue*)point;
- (void)tap:(NSValue*)point;
- (_Bool)_dragFrom:(id)arg1 to:(id)arg2 forDuration:(double)arg3 withTouchCount:(int)arg4 withFlick:(_Bool)arg5;
- (_Bool)_tapRequiredObject:(id)arg1 tapCount:(double)arg2 touchCount:(double)arg3;
- (_Bool)_tapOptionalObject:(id)arg1 tapCount:(double)arg2 touchCount:(double)arg3 tapOffset:(id)arg4;
- (id)localizedStringForKey:(id)arg1 value:(id)arg2 table:(id)arg3 bundlePath:(id)arg4;
- (id)localizedStringForKey:(id)arg1 withOptions:(id)arg2;
- (id)localizedStringForKey:(id)arg1;
- (id)scriptingSynonymStrings;
- (id)scriptingSynonyms;
- (id)scriptingFavoredSynonymString;
- (_Bool)_trackValueChanges:(_Bool)arg1;
- (_Bool)_handleAnnouncement:(id)arg1;
- (_Bool)_handleAlert;
- (void)setPassiveEventListeningMode:(id)arg1 withDelay:(id)arg2;
- (id)delegate;
- (void)setDelegate:(id)delegate;
- (unsigned long long)verboseOptions;
- (void)setVerboseOptions:(unsigned long long)arg1;
- (_Bool)delayForTimeInterval:(double)arg1;
- (double)popPatience;
- (void)pushPatience:(double)arg1;
- (void)setPatience:(double)arg1;
- (double)patience;
- (id)uiaxSpringBoardElement;
- (id)uiaxSystemAppElement;
- (id)uiaxSystemWideElement;
- (UIAElementArray*)elements;
- (UIARemote*)remote;
- (UIAScreen*)mainScreen;
- (UIAApplication*)springboard;
- (UIAApplication*)frontMostApp;
- (id)accessibilityUI;
- (id)systemApp;
- (id)applicationAtPoint:(id)arg1;
- (id)_applicationAtPosition:(struct CGPoint)arg1;
- (NSArray*)applications;
- (id)host;
- (void)setTextViewValueMaxLength:(long long)arg1;
- (long long)textViewValueMaxLength;
- (void)setTargetClipboard:(id)arg1;
- (id)targetClipboard;
- (void)captureStarkRect:(id)arg1 withName:(id)arg2;
- (void)captureRect:(id)arg1 withName:(id)arg2;
- (void)captureRect:(id)arg1 onScreen:(id)arg2 withName:(id)arg3;
- (id)imageFromRect:(struct CGRect)arg1;
- (void)captureStarkScreenWithName:(id)arg1;
- (void)captureScreenWithName:(id)arg1;
- (id)lastCommandTime;
- (double)upTime;
- (id)startupDate;
//Location is a dict of strings with special keys: @{@"latitude":@"37.332", @"longitude":@"-122.030" }
- (BOOL)setLocation:(NSDictionary*)location withOptions:(NSDictionary*)options;
- (BOOL)setLocation:(NSDictionary*)location;
- (BOOL)setDeviceOrientation:(NSNumber*)orientation; // @see UIDeviceOrientation
- (NSNumber*)deviceOrientation; // @see UIDeviceOrientation
- (NSString*)localeName;
- (NSString*)localeID;
- (id)languageName;
- (id)languageID;
- (NSString*)uniqueIdentifier;
- (NSString*)systemBuild;
- (NSString*)systemVersion;
- (NSString*)systemName;
- (NSString*)model;
- (NSString*)name;
- (id)rect;
- (_Bool)checkIsValid;
- (_Bool)isValid;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (void)_setLastAnimationEndedTime:(double)arg1;
- (double)_lastAnimationEndedTime;
- (long long)_interfaceOrientation;
- (void)_updateInterfaceOrientation;
- (void)_invalidate;
- (void)dealloc;
- (id)init;
- (id)_systemVersionDictionary;

@end

