//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSArray, NSMutableArray, SSAccount, SSKeyValueStore;

@interface SSAccountStore : NSObject
{
    NSObject<OS_dispatch_queue> *_dispatchQueue;
    SSKeyValueStore *_keyValueStore;
    NSObject<OS_dispatch_queue> *_notificationQueue;
    NSMutableArray *_notifyTokens;
}

+ (void)setDefaultStore:(id)arg1;
+ (void)resetExpirationForTokenType:(long long)arg1;
+ (void)resetExpiration;
+ (_Bool)isExpiredForTokenType:(long long)arg1;
+ (_Bool)isExpired;
+ (id)existingDefaultStore;
+ (double)tokenExpirationInterval;
+ (id)defaultStore;
- (void)_postAccountStoreChangeNotification;
- (id)_keyValueStore;
//- (void)_dispatchSync:(CDUnknownBlockType)arg1;
//- (void)_dispatchAsync:(CDUnknownBlockType)arg1;
- (void)signOutAllAccounts;
- (void)signOutAccount:(id)arg1;
//- (void)setDefaultAccountName:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)setActiveLockerAccount:(SSAccount*)account;
- (id)setActiveAccount:(SSAccount*)account;
- (void)setAccountCredits:(id)arg1 forAccountWithUniqueIdentifier:(id)arg2;
- (void)resetExpirationForTokenType:(long long)arg1;
- (void)resetExpiration;
- (void)reloadAccounts;
- (_Bool)isExpiredForTokenType:(long long)arg1;
@property(readonly, getter=isAuthenticationActive) _Bool authenticationActive;
//- (void)getDefaultAccountNameUsingBlock:(CDUnknownBlockType)arg1;
- (id)addAccount:(id)arg1;
- (id)accountWithUniqueIdentifier:(id)arg1 reloadIfNecessary:(_Bool)arg2;
@property(readonly, getter=isExpired) _Bool expired;
@property(readonly) SSAccount *activeLockerAccount;
@property(readonly) SSAccount *activeAccount;
- (id)accountWithUniqueIdentifier:(id)arg1;
@property(readonly) NSArray *accounts;
- (void)dealloc;
- (id)init;

@end

